### ISSUE TITLE
Cluster selector ignores KUBECONFIG setting

### ISSUE THREAD

**Issue by richard-fairthorne** [kubeshop/monokle#2938]
**Describe the bug**
No matter what I set KUBECONFIG to, the cluster selector shows only clusters in ~/.kube/config.

Attempting to load a cluster with a different config file selected results in a complaint that the context does not exist.

**To Reproduce**
- open a project
- go to settings
  <img width="456" alt="Screenshot 2022-12-21 at 5 18 07 PM" src="https://user-images.githubusercontent.com/1225460/209013127-a24eac7b-d006-4ec5-9f6b-7395279639c7.png">
- enter an alternate kubeconfig file
  <img width="456" alt="Screenshot 2022-12-21 at 5 19 06 PM" src="https://user-images.githubusercontent.com/1225460/209013275-046314f1-42f6-4753-9c56-c993159a61fe.png">
- The dropdown still shows only the clusters from another file.
  <img width="356" alt="Screenshot 2022-12-21 at 5 19 43 PM" src="https://user-images.githubusercontent.com/1225460/209013382-0b73a128-7552-4b98-8977-9135b9e537c3.png">
- Press Load
- Monokle complains about missing context (because it's reading the wrong kubeconfi)
  <img width="393" alt="Screenshot 2022-12-21 at 5 21 22 PM" src="https://user-images.githubusercontent.com/1225460/209013580-a9f513e5-2333-4964-8004-f3042269e980.png">

**Expected behavior**
I expected to be able to choose from the contexts in the file I specified.

**Screenshots**

**Desktop (please complete the following information):**
- OS: osx Ventura
- Version 13.0.1
- Monokle 1.13.1

**Comment by topliceanurazvan** [comment]
Hello @richard-fairthorne, thank you for reporting this issue. We have already fixed the problem in this PR - https://github.com/kubeshop/monokle/pull/2909 - and will release a new patch in the near future. 

In the meantime, you can try the latest nightly build, which is available at the following link: https://github.com/kubeshop/monokle/releases/tag/v1.13.2-nightly-2022-12-22.0. 

We appreciate your report and hope that the issue has been resolved. 🙌🏻

**Comment by richard-fairthorne** [comment]
Thanks. The problem appears to be partially fixed.

After loading the nightly, I was still unable to access my cluster (the dropdown had not updated to reflect what is in the selected file).

In order for it to work, I had to switch config files, and then switch back again. It appears that monokle does not read the cluster config file on startup, but rather, only when you actually switch.

As a result, changes to the config file are not reflected when you reload monokle.

**Comment by topliceanurazvan** [comment]
Hey @richard-fairthorne, we've been fixing some problems with the kubeconfig in the latest releases. Can you tell us if you still have problems with it?

**Comment by devcatalin** [comment]
This should be fixed in the latest releases
